### PR TITLE
Future-2 is developed pls review

### PR DESCRIPTION
**Pull request by gsanthprakash**

### CODE REVIEW

**Comment by gspvsr** [comment]
check oneagain

**Comment by gsanthprakash** [comment]
yes checked once again, it seems good

**Comment by gspvsr** [comment]
few mode code is missing, forget password feature-2 is missing

**Comment by gsanthprakash** [comment]
add new future

**Comment by gspvsr** [comment]
everyting is good approving

**Review by gspvsr — APPROVED** [review]
everying this is reviewed, approving it

**Pull request merged**
